version: "2.4"
services:
  broker01:
    image: eclipse-temurin:17-jre-focal
    restart: always
    volumes:
      - ./docker/kafka_2.13-2.8.1:/kafka
    environment:
      - LOG_DIR=/var/log/kafka
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server01.properties
    depends_on:
      - zookeeper
    networks:
      - sandbox-net

  broker02:
    image: eclipse-temurin:17-jre-focal
    restart: always
    volumes:
      - ./docker/kafka_2.13-2.8.1:/kafka
    environment:
      - LOG_DIR=/var/log/kafka
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server02.properties
    depends_on:
      - zookeeper
    networks:
      - sandbox-net

  broker03:
    image: eclipse-temurin:17-jre-focal
    restart: always
    volumes:
      - ./docker/kafka_2.13-2.8.1:/kafka
    environment:
      - LOG_DIR=/var/log/kafka
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server03.properties
    depends_on:
      - zookeeper
    networks:
      - sandbox-net

  consumer01:
    image: kafka-inspection:0.0.1
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=consumer
      - JAVA_OPTS=-Dapp.container-name=consumer01 -Dapp.is-fail-consumer=false -Dapp.topic-replacas=2
    networks:
      - sandbox-net

  consumer02:
    image: kafka-inspection:0.0.1
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=consumer
      - JAVA_OPTS=-Dapp.container-name=consumer02 -Dapp.topic-replacas=2
    networks:
      - sandbox-net

  producer:
    image: kafka-inspection:0.0.1
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=producer
      - JAVA_OPTS=-Dapp.container-name=producer -Dapp.topic-replacas=2
    ports:
      - 8080:8080
    networks:
      - sandbox-net

  zoonavi:
    image: elkozmon/zoonavigator:latest
    restart: always
    ports:
      - 30001:9000
    depends_on:
      - zookeeper
    networks:
      - sandbox-net

  zookeeper:
    image: eclipse-temurin:17-jre-focal
    restart: always
    volumes:
      - ./docker/kafka_2.13-2.8.1:/kafka
    environment:
      - LOG_DIR=/var/log/kafka
    command: /kafka/bin/zookeeper-server-start.sh /kafka/config/zookeeper.properties
    networks:
      - sandbox-net

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - sandbox-net

  adminer:
    image: adminer:4.7.7-standalone
    command: php -S 0.0.0.0:8080 -t /var/www/html
    restart: always
    depends_on:
      - postgres
    ports:
      - 30002:8080
    networks:
      - sandbox-net

networks:
  sandbox-net:
    external: true
